### ISSUE TITLE
Error: The following formula cannot be installed from bottle and must be built from source.

### ISSUE THREAD

**Issue by 094459** [sebsto/xcodeinstall#4] opened 2022-09-06 09:15 UTC
**Describe the bug**
Following the README on installing the tool, I get the following error:

```
(base)  @094459  ~  brew install xcodeinstall
==> Downloading https://github.com/sebsto/xcodeinstall/archive/refs/tags/v0.1.ta
==> Downloading from https://codeload.github.com/sebsto/xcodeinstall/tar.gz/refs
                                                  #    #     #=O=#
==> Installing xcodeinstall from sebsto/macos
Error: The following formula cannot be installed from bottle and must be
built from source.
  xcodeinstall
Install the Command Line Tools:
  xcode-select --install
```

**To Reproduce**

```
brew install xcodeinstall
```
**Screenshots**
```
(base)  @094459  ~  brew install xcodeinstall
==> Downloading https://github.com/sebsto/xcodeinstall/archive/refs/tags/v0.1.ta
==> Downloading from https://codeload.github.com/sebsto/xcodeinstall/tar.gz/refs
                                                  #    #     #=O=#
==> Installing xcodeinstall from sebsto/macos
Error: The following formula cannot be installed from bottle and must be
built from source.
  xcodeinstall
Install the Command Line Tools:
  xcode-select --install
```

**Desktop (please complete the following information):**
 - OS: Monteray 12.5.1
 - xcodeinstall version 0.1

**Comment by sebsto** [comment] 2022-09-06 09:27
Thank you for reporting this. Do you have development tools installed on your machine ?
I should probably switch to distributing binaries instead of the source code.

**Comment by 094459** [comment] 2022-09-06 09:59
Which development tools specifically? I have VSCode but I do not have Xcode installed.

**Comment by sebsto** [comment] 2022-09-06 10:43
OK, it might make sense to not have Xcode installed when using a tool to install it :-) 

I just published v02 that install the binaries instead of compiling from source.

To install v0.2
```
brew upgrade
brew install xcodeinstall
```

If this works for you - I'll proceed and close this issue.

**Comment by 094459** [comment] 2022-09-06 11:08
When I do that this time, I get the following: 
```
==> Downloading https://github.com/sebsto/xcodeinstall/archive/refs/tags/v0.2.tar.gz
==> Downloading from https://codeload.github.com/sebsto/xcodeinstall/tar.gz/refs/tags/
                      #    #     #     #                                -=O=-
==> Installing xcodeinstall from sebsto/macos
Error: The following formula cannot be installed from bottle and must be
built from source.
  xcodeinstall
Install the Command Line Tools:
  xcode-select --install
```

**Comment by sebsto** [comment] 2022-09-06 11:59
Root cause found - the brew formulae only provides arm64 binaries.  It can not install on x86 machines at the moment 
Going to follow up on this one : https://github.com/sebsto/xcodeinstall/issues/5

**Closed by sebsto** 2022-09-06 12:00 UTC
